# -*- coding: utf-8 -*-
"""Economic Analysis of Health Impact.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Dv2h8hgx9aMyYlfohXesjY_n3WuX1zjN
"""

import pandas as pd
import matplotlib.pyplot as plt

# Healthcare cost data for various diseases
data = {
    'Disease': ['CVD', 'Osteoporosis', 'Dementia', 'Breast Cancer'],
    'Cost': [10000, 10640, 15000, 30000,],  # Example values in USD
    'Net_Effect': [1200, 800, 600, 400]  # Example values from the graph
}

# Creating a DataFrame
df = pd.DataFrame(data)

# Calculating direct healthcare costs
df['Direct_Costs'] = df['Cost'] * df['Net_Effect']

# Calculating indirect costs ( 20% of direct costs)
df['Indirect_Costs'] = df['Direct_Costs'] * 0.2

# Visualization
plt.figure(figsize=(12, 6))
plt.bar(df['Disease'], df['Direct_Costs'], color='blue', alpha=0.6, label='Direct Costs')
plt.bar(df['Disease'], df['Indirect_Costs'], color='orange', alpha=0.6, label='Indirect Costs')
plt.title('Healthcare Costs and Indirect Expenses Analysis')
plt.ylabel('Costs (in USD)')
plt.xlabel('Diseases')
plt.legend()
plt.xticks(rotation=45)
plt.show()

# Exporting data to CSV
df.to_csv('healthcare_costs.csv', index=False)